# Generated by Django 3.2.18 on 2023-03-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('banner_picture', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
