# Generated by Django 3.2.18 on 2023-04-13 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='displayName',
        ),
    ]
