# Generated by Django 3.2.18 on 2023-03-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_info', '0002_auto_20230313_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=45),
        ),
    ]
