# Generated by Django 3.2.18 on 2023-04-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_info', '0004_alter_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beltcolor',
            old_name='id',
            new_name='belt_color_id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='id',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='id',
            new_name='comment_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='id',
            new_name='profile_id',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='id',
            new_name='tag_id',
        ),
    ]
