# Generated by Django 3.2.18 on 2023-04-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_info', '0005_auto_20230413_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app_info.profile'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app_info.tag'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PostTag',
        ),
    ]
