# Generated by Django 3.2.18 on 2023-04-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_info', '0007_alter_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='app_info.Tag'),
        ),
    ]
