# Generated by Django 3.2.18 on 2023-04-13 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_info', '0008_auto_20230413_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='app_info.post'),
            preserve_default=False,
        ),
    ]
